CREATE TABLE enrollment_2023 PARTITION OF enrollment
FOR VALUES FROM ('2023-01-01') TO ('2024-01-01');

CREATE TABLE enrollment_2024 PARTITION OF enrollment
FOR VALUES FROM ('2024-01-01') TO ('2025-01-01');

CREATE TABLE enrollment_2025 PARTITION OF enrollment
FOR VALUES FROM ('2025-01-01') TO ('2026-01-01');

CREATE TABLE enrollment_2026 PARTITION OF enrollment
FOR VALUES FROM ('2026-01-01') TO ('2027-01-01');

CREATE TABLE enrollment_other PARTITION OF enrollment
DEFAULT;

CREATE TABLE flow_active PARTITION OF flow
FOR VALUES IN ('active');

CREATE TABLE flow_archived PARTITION OF flow
FOR VALUES IN ('archived');

CREATE TABLE flow_other PARTITION OF flow
DEFAULT;

CREATE TABLE user_p0 PARTITION OF "user"
FOR VALUES WITH (MODULUS 4, REMAINDER 0);

CREATE TABLE user_p1 PARTITION OF "user"
FOR VALUES WITH (MODULUS 4, REMAINDER 1);

CREATE TABLE user_p2 PARTITION OF "user"
FOR VALUES WITH (MODULUS 4, REMAINDER 2);

CREATE TABLE user_p3 PARTITION OF "user"
FOR VALUES WITH (MODULUS 4, REMAINDER 3);